apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/urls: '["https://foresight-airflow-771179250808.us-central1.run.app","https://foresight-airflow-6ool3rlbea-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
    goog-terraform-provisioned: 'true'
  name: foresight-airflow
  namespace: '771179250808'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 554.0.0
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/sessionAffinity: 'false'
      labels:
        client.knative.dev/nonce: focisdbtgo
        run.googleapis.com/startupProbeType: Custom
    spec:
      containerConcurrency: 160
      containers:
      - env:
        - name: _AIRFLOW_WWW_USER_USERNAME
          value: admin
        - name: _AIRFLOW_WWW_USER_PASSWORD
          value: admin123
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: sqlite:////opt/airflow/data/airflow.db
        image: us-central1-docker.pkg.dev/financial-distress-ew/foresight/airflow:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
        startupProbe:
          failureThreshold: 20
          initialDelaySeconds: 60
          periodSeconds: 15
          tcpSocket:
            port: 8080
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /opt/airflow/data
          name: airflow-db
      serviceAccountName: foresight-ml-airflow-dev@financial-distress-ew.iam.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 512Mi
        name: airflow-db
  traffic:
  - latestRevision: true
    percent: 100
