steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/foresight/mlflow:${_IMAGE_TAG}",
        "-f",
        "deployment/docker/Dockerfile.mlflow",
        ".",
      ]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/foresight/mlflow:${_IMAGE_TAG}"
substitutions:
  _REGION: "us-central1"
  _IMAGE_TAG: "latest"
